version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    tty: true
    environment:
      - DJANGO_SUPERUSER_USERNAME=root
      - DJANGO_SUPERUSER_PASSWORD=1234
      - DJANGO_SUPERUSER_EMAIL=root@gmail.com

volumes:
  mysql: