# Generated by Django 4.0.5 on 2022-06-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryAddress',
            field=models.CharField(max_length=128, verbose_name='Delivery address'),
        ),
    ]
